### ISSUE TITLE
Implement module for diffing two repositories.yml files

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur-oss-suite-release#75]
AC:
- [ ] Using a baseline repositories yml file (`CURRENT_VER`), you can use a second repositories yml file (`NEW_VER`) to determine what versions should be included in the release and changelog. The output of those release notes and changelog would include all versions of a component betwen `version` in `NEW_VER` yaml up-to-but-excluding `version` in `CURRENT_VER` yaml.

Eg:

`repositories_current.yml`
```yaml
...
    repos:
...
      - name: cyberark/conjur-oss-helm-chart
        url: https://github.com/cyberark/conjur-oss-helm-chart
        description: Helm chart for deploying Conjur OSS.
        version: v1.3.7
...
```

`repositories_new.yml`
```yaml
...
    repos:
...
      - name: cyberark/conjur-oss-helm-chart
        url: https://github.com/cyberark/conjur-oss-helm-chart
        description: Helm chart for deploying Conjur OSS.
        version: v2.1.1
...
```

The resulting changelog and release notes would include all released changes in the `cyberark/conjur-oss-helm-chart` repo from version `v2.1.1` down to (but excluding) `v1.3.7`.
